[package]
name = "bootram"
version = "0.1.0"
authors = ["Amber Bertucci <amber@akarys.me>"]
edition = "2018"

[lib]
path = "bootram/bootram.rs"
name = "bootram"
crate-type = ["staticlib"]

[dependencies]
buddy_system_allocator = "0.8.0"
