[package]
name = "bootram"
version = "0.1.0"
authors = ["Matteo Bertucci <matteobertucci2004@gmail.com>"]
edition = "2018"

[lib]
path = "bootram/bootram.rs"
name = "bootram"
crate-type = ["staticlib"]
